[tool.poetry]
name = "botDiscordSpammer"
version = "0.1.0"
description = ""
authors = ["Rodrigo Cordeiro (https://rodcordeiro.com.br)"]

[tool.poetry.dependencies]
python = "^3.10"
python-decouple = "^3.8"
selenium = "^4.8.3"

[tool.poetry.dev-dependencies]

[build-system]
